-- Tabla BASE
CREATE TABLE BASE (
    ID_Base INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

-- Tabla AVION
CREATE TABLE AVION (
    ID_Avion INT AUTO_INCREMENT PRIMARY KEY,
    Codigo VARCHAR(10) NOT NULL,
    Tipo VARCHAR(50) NOT NULL,
    ID_Base INT NOT NULL,
    FOREIGN KEY (ID_Base) REFERENCES BASE(ID_Base) ON DELETE CASCADE
);

-- Tabla PERSONA (Superclase)
CREATE TABLE PERSONA (
    ID_Persona INT AUTO_INCREMENT PRIMARY KEY,
    Codigo VARCHAR(10) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Apellido VARCHAR(100) NOT NULL,
    ID_Base INT NOT NULL,
    FOREIGN KEY (ID_Base) REFERENCES BASE(ID_Base) ON DELETE CASCADE
);

-- Tabla PILOTO (Subclase de PERSONA)
CREATE TABLE PILOTO (
    ID_Piloto INT PRIMARY KEY,
    Horas_Vuelo INT NOT NULL,
    FOREIGN KEY (ID_Piloto) REFERENCES PERSONA(ID_Persona) ON DELETE CASCADE
);

-- Tabla MIEMBRO (Subclase de PERSONA)
CREATE TABLE MIEMBRO (
    ID_Miembro INT PRIMARY KEY,
    FOREIGN KEY (ID_Miembro) REFERENCES PERSONA(ID_Persona) ON DELETE CASCADE
);

-- Tabla VUELO
CREATE TABLE VUELO (
    ID_Vuelo INT AUTO_INCREMENT PRIMARY KEY,
    Num_Vuelo VARCHAR(20) NOT NULL,
    Origen VARCHAR(100) NOT NULL,
    Destino VARCHAR(100) NOT NULL,
    Hora TIME NOT NULL,
    Fecha DATE NOT NULL,
    ID_Avion INT NOT NULL,
    ID_Piloto INT NOT NULL,
    FOREIGN KEY (ID_Avion) REFERENCES AVION(ID_Avion) ON DELETE CASCADE,
    FOREIGN KEY (ID_Piloto) REFERENCES PILOTO(ID_Piloto) ON DELETE CASCADE
);

-- Tabla TRIPULACION (Relación entre MIEMBRO y VUELO)
CREATE TABLE TRIPULACION (
    ID_Vuelo INT NOT NULL,
    ID_Miembro INT NOT NULL,
    PRIMARY KEY (ID_Vuelo, ID_Miembro),
    FOREIGN KEY (ID_Vuelo) REFERENCES VUELO(ID_Vuelo) ON DELETE CASCADE,
    FOREIGN KEY (ID_Miembro) REFERENCES MIEMBRO(ID_Miembro) ON DELETE CASCADE
);
